#!/bin/bash

DIR=$1
FASQ_DIRS=$2
R1_FILES=$3
R2_FILES=$4
FLOWCELLS=$5
LANES=$6
PLATFORM=$7
LIBRARY_NAME=$8
RUN_DATE=${9}
SM_TAG=${10}
CENTER=${11}
DESCRIPTION=${12}
WD_DIR=${DIR}/${SM_TAG}

#mkdir ${WD_DIR}


FILES=""

IFS=',' read -ra FASQ_DIRS_ARRAY <<< "${FASQ_DIRS}"
IFS=',' read -ra R1_FILES_ARRAY <<< "${R1_FILES}"
IFS=',' read -ra R2_FILES_ARRAY <<< "${R2_FILES}"
IFS=',' read -ra FLOWCELLS_ARRAY <<< "${FLOWCELLS}"
IFS=',' read -ra LANES_ARRAY <<< "${LANES}"

for i in {0..50}
do
    if [ ! -z "${FASQ_DIRS_ARRAY[${i}]}" ]
    then
        #./SCRIPTS/A_BWA.sh ${WD_DIR} ${FASQ_DIRS_ARRAY[${i}]} ${R1_FILES_ARRAY[${i}]} ${R2_FILES_ARRAY[${i}]} ${FLOWCELLS_ARRAY[${i}]} ${LANES_ARRAY[${i}]} ${PLATFORM} ${LIBRARY_NAME} ${RUN_DATE} ${SM_TAG} ${CENTER} ${DESCRIPTION}
        PLATFORM_UNIT=${FLOWCELLS_ARRAY[${i}]}.${LANES_ARRAY[${i}]}.${LIBRARY_NAME}
        FILES="${FILES}${WD_DIR}/${SM_TAG}_${PLATFORM_UNIT}.bam,"
    fi
done


#./SCRIPTS/A2_MERGE_BAM.sh /scratch/PIPELINE/BH15941_1_1 BH15941_1_1 /scratch/PIPELINE/BH15941_1_1/BH15941_1_1_HGLTFDSX7.L3.CKDN230021664-1A.bam,/scratch/PIPELINE/BH15941_1_1/BH15941_1_1_HCN75DSX7.L1.CKDN230021664-1A.bam

./SCRIPTS/A2_MERGE_BAM.sh $WD_DIR $SM_TAG ${FILES%?}
./SCRIPTS/B_SORT.sh ${SM_TAG} ${WD_DIR} 
./SCRIPTS/C_MARK_DUP.sh ${SM_TAG} ${WD_DIR}
./SCRIPTS/D_REALIGN.sh ${SM_TAG} ${WD_DIR} 
./SCRIPTS/E_BQSR.sh ${SM_TAG} ${WD_DIR}  
./SCRIPTS/F_FINAL_BAM.sh ${SM_TAG} ${WD_DIR} 
./SCRIPTS/G_HAPLOTYPE_CALLER_QC.sh ${SM_TAG} ${WD_DIR} 
#./SCRIPTS/I_ANNOVAR.sh ${WD_DIR} ${SM_TAG}_QC_FILTERED_OnBait

