#/bin/bash
#SOBREIRA LAB WES PIPELINE v1.0
#09.15.2023
#RENAN PAULO MARTIN
#rmart120@jhmi.edu

REF_GENOME="/scratch/PIPELINE/TOOLS/FILES/human_g1k_v37_decoy.fasta"

WD_DIR=$1
FASQ_DIR=$2
R1_FILE=$3
R2_FILE=$4
FLOWCELL=$5
LANE=$6
PLATFORM=$7
LIBRARY_NAME=$8
RUN_DATE=${9}
SM_TAG=${10}
CENTER=${11}
DESCRIPTION=${12}
PLATFORM_UNIT=${FLOWCELL}.${LANE}.${LIBRARY_NAME}


bwa mem -M -t 4 ${REF_GENOME} ${FASQ_DIR}/${R1_FILE} ${FASQ_DIR}/${R2_FILE} \
-R "@RG\tID:$FLOWCELL"_"$LANE\tPU:$PLATFORM_UNIT\tPL:$PLATFORM\tLB:$LIBRARY_NAME\tDT:$RUN_DATE\tSM:$SM_TAG\tCN:$CENTER\tDS:$DESCRIPTION" >| ${WD_DIR}/${SM_TAG}_${PLATFORM_UNIT}.bam



